export const INSTITUTIONS = {
    public_universities: [
        "University of Cape Town (UCT)",
        "University of the Witwatersrand (Wits)",
        "University of Pretoria (UP)",
        "Stellenbosch University (SU)",
        "University of KwaZulu-Natal (UKZN)",
        "University of Johannesburg (UJ)",
        "North-West University (NWU)",
        "University of the Western Cape (UWC)",
        "Rhodes University",
        "Nelson Mandela University (NMU)",
        "University of the Free State (UFS)",
        "University of Limpopo (UL)",
        "University of Fort Hare (UFH)",
        "Tshwane University of Technology (TUT)",
        "Cape Peninsula University of Technology (CPUT)",
        "Durban University of Technology (DUT)",
        "Vaal University of Technology (VUT)",
        "Central University of Technology (CUT)",
        "Mangosuthu University of Technology (MUT)",
        "UNISA (University of South Africa)",
        "Walter Sisulu University (WSU)",
        "University of Zululand (UniZulu)",
        "University of Venda (Univen)",
        "Sol Plaatje University (SPU)",
        "University of Mpumalanga (UMP)"
    ],
    tvet_colleges: [
        "Orbit TVET College",
        "Majuba TVET College",
        "False Bay TVET College",
        "College of Cape Town",
        "Northlink TVET College",
        "South West Gauteng TVET College",
        "Tshwane North TVET College",
        "Tshwane South TVET College",
        "Ekurhuleni East TVET College",
        "Ekurhuleni West TVET College",
        "Sedibeng TVET College",
        "Mopani South East TVET College",
        "Vhembe TVET College",
        "Capricorn TVET College",
        "Waterberg TVET College",
        "Sekhukhune TVET College",
        "Buffalo City TVET College",
        "Lovedale TVET College",
        "Ikhala TVET College",
        "Port Elizabeth TVET College",
        "Eastcape Midlands TVET College",
        "King Hintsa TVET College",
        "Ingwe TVET College",
        "Coastal KZN TVET College",
        "Thekwini TVET College",
        "Umgungundlovu TVET College",
        "Esayidi TVET College",
        "Mnambithi TVET College",
        "Mthashana TVET College",
        "Nkangala TVET College",
        "Gert Sibande TVET College",
        "Ehlanzeni TVET College",
        "Goldfields TVET College",
        "Motheo TVET College",
        "Flavius Mareka TVET College",
        "Northern Cape Urban TVET College",
        "Northern Cape Rural TVET College"
    ],
    private_colleges: [
        "Rosebank College",
        "Vega School",
        "Varsity College",
        "Damelin",
        "Boston City Campus",
        "Richfield Graduate Institute of Technology",
        "STADIO Higher Education",
        "Regent Business School",
        "MANCOSA",
        "Cornerstone Institute",
        "Inscape",
        "Red & Yellow Creative School of Business",
        "AAA School of Advertising",
        "Eduvos",
        "CTI Education Group",
        "Lyceum College"
    ],
    online_platforms: [
        "Coursera (Professional Certificates)",
        "Udemy (Skill-based courses)",
        "Google Career Certificates (Grow with Google)",
        "LinkedIn Learning",
        "edX (University-level online courses)",
        "GetSmarter (Short courses from top unis)",
        "Udacity (Tech Nanodegrees)",
        "Pluralsight (Tech skills)",
        "Alison (Free online courses)",
        "FutureLearn",
        "Codecademy",
        "HyperionDev (Coding Bootcamps)",
        "AWS Training & Certification",
        "Microsoft Learn",
        "Cisco Networking Academy"
    ]
};

export const FUNDING_SOURCES = [
    "NSFAS (National Student Financial Aid Scheme)",
    "Funza Lushaka Bursary (Teaching)",
    "ISFAP (Missing Middle Funding)",
    "Department of Social Development Bursary",
    "Transnet Bursary Scheme",
    "Sasol Bursaries",
    "Investec Bursary",
    "Standard Bank Group Bursary",
    "Allan Gray Orbis Foundation",
    "Thuthuka Bursary Fund (Accounting)",
    "Motsepe Foundation Bursary",
    "Vodacom Bursary Scheme",
    "MTN Bursaries",
    "Telkom Bursaries",
    "Eskom Bursaries"
];
