import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';

const TermsPage: React.FC = () => {
    return (
        <div className="max-w-4xl mx-auto py-8 px-4">
            <Link to="/" className="inline-flex items-center text-primary-600 hover:text-primary-700 mb-6">
                <ArrowLeft className="w-4 h-4 mr-2" />
                Back to Home
            </Link>

            <div className="glass-card p-8 md:p-12 rounded-3xl">
                <h1 className="text-4xl font-bold text-gray-900 mb-6">Terms of Service</h1>
                <p className="text-sm text-gray-500 mb-8">Last updated: {new Date().toLocaleDateString('en-ZA', { day: 'numeric', month: 'long', year: 'numeric' })}</p>

                <div className="prose prose-lg max-w-none">
                    <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">1. Acceptance of Terms</h2>
                    <p className="text-gray-700 leading-relaxed mb-6">
                        By accessing and using CareerPath.AI ("the Service"), you accept and agree to be bound by these Terms of Service.
                        If you do not agree to these terms, please do not use the Service.
                    </p>

                    <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">2. Description of Service</h2>
                    <p className="text-gray-700 leading-relaxed mb-6">
                        CareerPath.AI provides AI-powered career guidance, educational course recommendations, and university/college matching
                        services for South African students based on their matric results and APS scores.
                    </p>

                    <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">3. AI-Generated Recommendations Disclaimer</h2>
                    <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 mb-6">
                        <p className="text-yellow-800 font-medium">
                            <strong>IMPORTANT:</strong> All course recommendations, career suggestions, and admissions information provided by
                            CareerPath.AI are generated by artificial intelligence and should be used as guidance only. We strongly recommend:
                        </p>
                        <ul className="list-disc ml-6 mt-3 text-yellow-800">
                            <li>Verify all information directly with the relevant institution</li>
                            <li>Confirm application deadlines and requirements</li>
                            <li>Check current course availability and accreditation</li>
                        </ul>
                    </div>

                    <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">4. Payment Terms</h2>
                    <p className="text-gray-700 leading-relaxed mb-4">
                        Access to premium features requires a one-time payment of R120.00. By making this payment, you agree that:
                    </p>
                    <ul className="list-disc ml-6 text-gray-700 space-y-2 mb-6">
                        <li>Payment verification is processed via AI visual recognition</li>
                        <li>Payments are final and non-refundable once premium access is granted</li>
                        <li>You are responsible for providing accurate payment proof</li>
                    </ul>

                    <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">5. User Responsibilities</h2>
                    <p className="text-gray-700 leading-relaxed mb-4">You agree to:</p>
                    <ul className="list-disc ml-6 text-gray-700 space-y-2 mb-6">
                        <li>Provide accurate information, especially your matric results</li>
                        <li>Not misuse the Service for fraudulent purposes</li>
                        <li>Not attempt to circumvent payment or security measures</li>
                        <li>Keep your account credentials secure</li>
                    </ul>

                    <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">6. Limitation of Liability</h2>
                    <p className="text-gray-700 leading-relaxed mb-6">
                        CareerPath.AI and its operators shall not be held liable for:
                    </p>
                    <ul className="list-disc ml-6 text-gray-700 space-y-2 mb-6">
                        <li>Decisions made based on AI-generated recommendations</li>
                        <li>Changes to university/college requirements after information was provided</li>
                        <li>Application rejections or missed deadlines</li>
                        <li>Inaccuracies in third-party information (bursaries, deadlines)</li>
                    </ul>

                    <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">7. Intellectual Property</h2>
                    <p className="text-gray-700 leading-relaxed mb-6">
                        All content, features, and functionality of the Service are owned by CareerPath.AI and protected by copyright and
                        trademark laws.
                    </p>

                    <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">8. Modifications to Service</h2>
                    <p className="text-gray-700 leading-relaxed mb-6">
                        We reserve the right to modify, suspend, or discontinue any part of the Service at any time without prior notice.
                    </p>

                    <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">9. Governing Law</h2>
                    <p className="text-gray-700 leading-relaxed mb-6">
                        These Terms shall be governed by the laws of South Africa. Any disputes shall be resolved in South African courts.
                    </p>

                    <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">10. Contact Information</h2>
                    <p className="text-gray-700 leading-relaxed mb-6">
                        For questions about these Terms of Service, please contact us at support@careerpath.ai
                    </p>
                </div>
            </div>
        </div>
    );
};

export default TermsPage;
